/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panchis.vistas;

import com.panchis.dao.Crud_HistorialVentas;
import com.panchis.controlador.Ctrl_HistorialVentas;
import java.io.IOException;


/**
 *
 * @author Jean
 */
public class FrmHistorialVentas extends javax.swing.JPanel {

    /**
     * Creates new form Cliente
     */
    public FrmHistorialVentas() {
        initComponents();
        //cargar tabla c
        Ctrl_HistorialVentas controlador = new Ctrl_HistorialVentas(this);
        Crud_HistorialVentas.CargarComboClientes();
        Crud_HistorialVentas.CargarTablaVentas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ventas = new javax.swing.JTable();
        btn_filtrar = new javax.swing.JButton();
        jButton_ExporExcel = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("HISTORIAL DE VENTAS ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 24, -1, -1));

        jTable_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "N°", "Nombre", "Apellido"
            }
        ));
        jScrollPane1.setViewportView(jTable_ventas);
        if (jTable_ventas.getColumnModel().getColumnCount() > 0) {
            jTable_ventas.getColumnModel().getColumn(0).setResizable(false);
            jTable_ventas.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 90, 910, 378));

        btn_filtrar.setBackground(new java.awt.Color(255, 204, 0));
        btn_filtrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_filtrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/panchis/imagenes/filtrar.png"))); // NOI18N
        btn_filtrar.setText("FILTRAR");
        btn_filtrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn_filtrar.setBorderPainted(false);
        btn_filtrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 17, 126, 48));

        jButton_ExporExcel.setBackground(new java.awt.Color(255, 204, 0));
        jButton_ExporExcel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton_ExporExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/panchis/imagenes/Ex.png"))); // NOI18N
        jButton_ExporExcel.setText("EXPORTAR EXCEL");
        jButton_ExporExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExporExcelActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_ExporExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExporExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExporExcelActionPerformed
         ExportarExcel obj;
        try {
            obj = new ExportarExcel();
            obj.exportarExcel(jTable_ventas);
            } catch (IOException ex) {
                System.out.println("Erro " + ex);
            }
        
    }//GEN-LAST:event_jButton_ExporExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_filtrar;
    private javax.swing.JButton jButton_ExporExcel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_ventas;
    // End of variables declaration//GEN-END:variables

   
}
